### ISSUE TITLE
note.object can't compile in SJTextViewAttachmentsController

### ISSUE THREAD

**Issue by LustySwimmer** [sebj/Kit#2]
Thanks for your categories, but something went wrong when I drag SJTextViewAttachmentsController into my project, It lies to number 64 in SJTextViewAttachmentsController, can't find note

**Comment by LustySwimmer** [comment]
I just found that It come from a deprecated method textStorageWillProcessEditing with parameter note, which has no use in SJTextViewAttachmentsController

**Comment by sebj** [comment]
Whoops, that was indeed a leftover from the old deprecated `textStorageWillProcessEditing:` method. Good spot, I'll fix that!
